# Generated by Django 3.0 on 2019-12-17 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Specialist.SpecialistCategory')),
            ],
        ),
    ]
