# Generated by Django 3.0 on 2019-12-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist', '0002_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('level', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='specialist',
            name='sex',
            field=models.CharField(max_length=6),
        ),
        migrations.CreateModel(
            name='ProjectSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist.Project')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist.Specialist')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialist.UserInfo'),
        ),
    ]
